# h2 http://localhost:8080/h2-console
spring:
   jpa:
      database: POSTGRESQL 
   datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/studio
      username: studio

debug: true
image:
  local: true