spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
   multipart:
     max-file-size: 20MB
     max-request-size: 20MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.client.id}
            client-secret: ${google.client.secret}
    mail:
      default-encoding: UTF-8
      protocol: smtp
      host: ${spring.mail.host}
      port: ${spring.mail.port}
      username: ${spring.mail.username}
      password: ${spring.mail.password}
      properties: 
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
  thymeleaf:
    check-template-location: false
image:
  local: true
